### ISSUE TITLE
"Biomass CHP (existing)" in electricity_variables.yaml

### ISSUE THREAD

**Issue by Stew-McD** [polca/premise#127]
When running consequential databases, the proxy for this technology "Biomass CHP (existing)" cannot by found by wurst when it looks for it based on the criteria in electricity_variables.yaml. 

### WORKAROUND 
change line 45 
`  exists in database: False`
to
  'exists in database: True'

so that premise doesn't try and look for a proxy.

### ERROR
```
/////////////////////////// ELECTRICITY ////////////////////////////
Traceback (most recent call last):
  File "/home/stew/code/gh/WasteAndMaterialFootprint/src/WasteAndMaterialFootprint/main.py", line 309, in <module>
    main()
  File "/home/stew/code/gh/WasteAndMaterialFootprint/src/WasteAndMaterialFootprint/main.py", line 106, in main
    FutureScenarios()
  File "/home/stew/code/gh/WasteAndMaterialFootprint/src/WasteAndMaterialFootprint/FutureScenarios.py", line 161, in FutureScenarios
    ndb.update_electricity()
  File "/home/stew/code/gh/premise/premise/ecoinvent_modification.py", line 881, in update_electricity
    scenario, self.modified_datasets, _ = _update_electricity(
  File "/home/stew/code/gh/premise/premise/electricity.py", line 186, in _update_electricity
    electricity.create_missing_power_plant_datasets()
  File "/home/stew/code/gh/premise/premise/electricity.py", line 2038, in create_missing_power_plant_datasets
    new_datasets = self.fetch_proxies(
  File "/home/stew/code/gh/premise/premise/transformation.py", line 585, in fetch_proxies
    d_iam_to_eco = self.region_to_proxy_dataset_mapping(
  File "/home/stew/code/gh/premise/premise/transformation.py", line 553, in region_to_proxy_dataset_mapping
    fallback_loc = list(d_map.values())[0]
IndexError: list index out of range
```
### source in electricity_variables.yaml

```
Biomass CHP (existing):
  iam_aliases:
    tiam: Secondary Energy|Electricity|Biomass existing capacity|w/o CCS
  eff_aliases:
    tiam: Efficiency|Electricity|Existing biomass|w/o CCS
  ecoinvent_aliases:
    fltr:
      - heat and power co-generation, existing, wood chips
    mask:
      reference product:
        - heat
        - label
        - renewable
  ecoinvent_fuel_aliases:
    fltr:
      - market for wood chips, wet, measured as dry mass
  exists in database: False
  proxy:
    name: heat and power co-generation, wood chips, 6667 kW
    reference product: electricity, high voltage
    mask:
      reference product:
        - heat
        - label
        - renewable
    new name: heat and power co-generation, existing, wood chips
```
Versions: bw2, wurst latest, premise from the master branch

**Comment by romainsacchi** [comment]
Thanks. Fixed with #126.
