### ISSUE TITLE
Location matching issue for STEEL.

### ISSUE THREAD

**Issue by tapajyoti-ghosh** [polca/premise#144]
Versions - 
```
brightway2==2.4.3
Brotli==1.1.0
bw-migrations==0.2
bw2analyzer==0.10
bw2calc==1.8.2
bw2data==3.6.6
bw2io==0.8.12
bw2parameters==1.1.0
premise==1.8.1
premise-gwp==0.9.6
constructive-geometries==0.9.5
```

**We are using ecoinvent 3.8**

```
/////////////////////// EXTRACTING IAM DATA ////////////////////////
Done!
38.76398992538452
new database created, updating now

////////////////////////////// STEEL //////////////////////////////
Cannot find the IAM location for YE from IAM model image.
Cannot find the IAM location for AL from IAM model image.
Cannot find the IAM location for US-WECC from IAM model image.
Cannot find the IAM location for CD from IAM model image.
Cannot find the IAM location for LK from IAM model image.
Cannot find the IAM location for CU from IAM model image.
Cannot find the IAM location for KG from IAM model image.
Cannot find the IAM location for PT from IAM model image.
Cannot find the IAM location for NZ from IAM model image.
Cannot find the IAM location for CN-NM from IAM model image.
Traceback (most recent call last):
  File "/Users/tghosh/Desktop/Dynamic-LCA-with-LiAISON/code/__main__.py", line 116, in <module>
    editor(updated_database = updated_database,
  File "/Users/tghosh/Desktop/Dynamic-LCA-with-LiAISON/code/image_ecoinvent_updater/main_database_editor.py", line 97, in editor
    ndb.update_steel()
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/ecoinvent_modification.py", line 1039, in update_steel
    scenario, self.modified_datasets, _ = _update_steel(
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/steel.py", line 16, in _update_steel
    steel = Steel(
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/steel.py", line 62, in __init__
    super().__init__(
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/transformation.py", line 288, in __init__
    self.ecoinvent_to_iam_loc: Dict[str, str] = {
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/transformation.py", line 289, in <dictcomp>
    loc: self.geo.ecoinvent_to_iam_location(loc)
  File "/Users/tghosh/miniconda3/envs/liaison/lib/python3.10/site-packages/premise/geomap.py", line 166, in ecoinvent_to_iam_location
    raise ValueError(f"Could not find equivalent for {location}.")
ValueError: Could not find equivalent for SAS.
Thu Jan 18 09:18:10 MST 2024
1 minutes and 16 seconds elapsed.
```

**Comment by tapajyoti-ghosh** [comment]
Resolved pip install wurst==0.3.5
