### ISSUE TITLE
Scenario LCA failed error!

### ISSUE THREAD

**Issue by iamz33** [polca/premise#98]
Couldn't perform scenario LCA results with superstructure sdf file on activity browser.

`Loading Scenario file. This may take a while for large files
Traceback (most recent call last):
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\calculations.py", line 37, in do_LCA_calculations
    mlca = SuperstructureMLCA(cs_name, df)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\mlca.py", line 37, in __init__
    assert not df.empty, "Filtering unused flows removed all of the scenario data."
AssertionError: Filtering unused flows removed all of the scenario data.`

**Comment by romainsacchi** [comment]
HI @iamz33 ,

can you tell me which scenarios you've created? 
Which was the ecoinvent db you used as a source?
Also, can you maybe share your SDF file?

Finally, which version of premise and AB are you using?

**Comment by iamz33** [comment]
Activity browser version 2.6.9
Premise version  1.4.1

Scenarios created: SSP2RCP26 model scenario for years 2020,2030,2040 and 2050.
This sdf file is created on base ecoinvent cutoff 3.8. Only updated electricity, transport and fuel sectors. 

Sharing the superstructure file in this link: 
https://docs.google.com/spreadsheets/d/18BkBa9xW_XtUnnmTlmIqtR0CwFQXElPd/edit?usp=sharing&ouid=116621899224969187015&rtpof=true&sd=true

**Comment by romainsacchi** [comment]
I'll start with a stupid question: can you confirm that the superstructure database you registered in AB is precisely called "my_supdb_ssp2rcp26_new"?

**Comment by iamz33** [comment]
Yes! It's exactly the same

**Comment by romainsacchi** [comment]
Could you share the db as well?
You can export it from the AB as a .bw2Package file.
You can send the share link directly to me r_s@me.com

**Comment by romainsacchi** [comment]
Could you try updating AB to v.2.7.3?

**Comment by iamz33** [comment]
(ab) C:\Users\Zee-Workstation>pip install activity-browser==2.7.3
ERROR: Could not find a version that satisfies the requirement activity-browser==2.7.3 (from versions: none)
ERROR: No matching distribution found for activity-browser==2.7.3


I see 2.7.3 version in latest releases of AB. But Is it only in developer version or something? Not sure. Tried that as well. 
(ab_dev) C:\Users\Zee-Workstation>pip install activity-browser==2.7.3
ERROR: Could not find a version that satisfies the requirement activity-browser==2.7.3 (from versions: none)
ERROR: No matching distribution found for activity-browser==2.7.3

**Comment by iamz33** [comment]
Ok. Successfully updated to AB version 2.7.3. It's not showing LCA failed error. However, still unable to generate results 

(ab) C:\Users\Zee-Workstation>activity-browser
-hiding tab: History

DevTools listening on ws://127.0.0.1:3999/devtools/browser/04caa8e7-faa5-4a82-ad86-3bc7593ffc69
-hiding tab: Activity Details
-hiding tab: Characterization Factors
-hiding tab: Graph Explorer
-hiding tab: LCA results
Reset project settings directory to: C:\Users\Zee-Workstation\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loading user settings:
dirpath already loaded
Reset project settings directory to: C:\Users\Zee-Workstation\AppData\Local\pylca\Brightway3\default.c21f969b5f03d33d43e04f8f136e7682
Loaded project: default
Brightway2 data directory: C:\Users\Zee-Workstation\AppData\Local\pylca\Brightway3
Brightway2 active project: default
Qt Version: 5.15.6
Remote debugging server started successfully. Try pointing a Chromium-based browser to http://127.0.0.1:3999
separator == ';'
Loading Scenario file. This may take a while for large files
<function get_header_index at 0x000001AA0D7E4700> -- 0.3256387710571289
<function import_from_excel at 0x000001AA0D7E48B0> -- 66.91838026046753
<function ScenarioImportWidget.sync_superstructure at 0x000001AA0E125040> -- 0.003000497817993164
<function ScenarioImportWidget.load_action at 0x000001AA0E11CEE0> -- 75.01521253585815
Traceback (most recent call last):
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 4436, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 211, in start_calculation
    'data': self.scenario_panel.combined_dataframe(),
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 336, in combined_dataframe
    manager = SuperstructureManager(*data)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 24, in __init__
    SuperstructureManager.format_dataframe(df)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 114, in format_dataframe
    df = SuperstructureManager.merge_flows_to_self(df)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 146, in merge_flows_to_self
    prod_amt = list(bw.get_activity(idx[0]).production())[0].get('amount', 1)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\bw2data\utils.py", line 335, in get_activity
    return Database(key[0]).get(key[1])
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\bw2data\backends\peewee\database.py", line 132, in get
    self._get_queryset(filters=False).where(
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 7075, in get
    raise self.model.DoesNotExist('%s instance matching query does '
bw2data.backends.peewee.schema.ActivityDatasetDoesNotExist: <Model: ActivityDataset> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."data", "t1"."code", "t1"."database", "t1"."location", "t1"."name", "t1"."product", "t1"."type" FROM "activitydataset" AS "t1" WHERE (("t1"."database" = ?) AND ("t1"."code" = ?)) ORDER BY Random() LIMIT ? OFFSET ?
Params: ['my_supdb_ssp2rcp26_new', 'edcde9a908a7f1ae04001bf4b4266b93', 1, 0]

Traceback (most recent call last):
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 7072, in get
    return clone.execute(database)[0]
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 4436, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 211, in start_calculation
    'data': self.scenario_panel.combined_dataframe(),
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\layouts\tabs\LCA_setup.py", line 336, in combined_dataframe
    manager = SuperstructureManager(*data)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 24, in __init__
    SuperstructureManager.format_dataframe(df)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 114, in format_dataframe
    df = SuperstructureManager.merge_flows_to_self(df)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\activity_browser\bwutils\superstructure\manager.py", line 146, in merge_flows_to_self
    prod_amt = list(bw.get_activity(idx[0]).production())[0].get('amount', 1)
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\bw2data\utils.py", line 335, in get_activity
    return Database(key[0]).get(key[1])
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\bw2data\backends\peewee\database.py", line 132, in get
    self._get_queryset(filters=False).where(
  File "C:\Users\Zee-Workstation\anaconda3\envs\ab\lib\site-packages\peewee.py", line 7075, in get
    raise self.model.DoesNotExist('%s instance matching query does '
bw2data.backends.peewee.schema.ActivityDatasetDoesNotExist: <Model: ActivityDataset> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."data", "t1"."code", "t1"."database", "t1"."location", "t1"."name", "t1"."product", "t1"."type" FROM "activitydataset" AS "t1" WHERE (("t1"."database" = ?) AND ("t1"."code" = ?)) ORDER BY Random() LIMIT ? OFFSET ?
Params: ['my_supdb_ssp2rcp26_new', 'edcde9a908a7f1ae04001bf4b4266b93', 1, 0]

**Comment by romainsacchi** [comment]
This tells us that the activity with the code `('my_supdb_ssp2rcp26_new', 'edcde9a908a7f1ae04001bf4b4266b93')` does not exist.

Using jupyter notebook and brightway directly, can you check if, within your project: 

````
bw.get_activity(('my_supdb_ssp2rcp26_new', 'edcde9a908a7f1ae04001bf4b4266b93'))
````

returns an activity?

**Comment by romainsacchi** [comment]
Closing the issue since the conversation is not active.
